spring:
  application:
    name: config-service
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath://configurations
        git:
          uri: https://github.com/ogak343/microservices-practice
          clone-on-start: true
          search-paths: config
          default-label: master
      override-system-properties: false

server:
  port: 8888
