spring:
  application:
    name: config-services
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath://configurations

server:
  port: 8888