spring:
  application:
    name: config-service
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath://configurations
        git:
          uri: https://github.com/ogak343/microservices-practice
          clone-on-start: true
          search-paths: config
          default-label: master
      override-system-properties: false

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  tracing:
    sampling:
      probability: 1.0

server:
  port: 8888
