spring:
  application:
    name: customer-service
  config:
    import: optional:configserver:127.0.0.1:8888
  datasource:
    url: jdbc:postgresql://127.0.0.1:5433/customer_db
    username: customer
    password: customer
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
  liquibase:
    default-schema: public
    liquibase-schema: public
    change-log: classpath:db/changelog/Initializer.xml
  data:
    redis:
      timeout: 30 #in minutes
      host: 127.0.0.1
      password: redis_password
      port: 6379
  cloud:
    openfeign:
      autoconfiguration:
        jackson:
          enabled: true
server:
  port: 8081

kafka:
  topic:
    email: topicEmail
    sms: topicSMS

jwt:
  expiresIn: 30
  secretKey: 9CA722EACC9EDE9639E2A26BBEFFEC3B8711
