version: '3.8'

services:
  product_db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: product_db
      POSTGRES_USER: product
      POSTGRES_PASSWORD: product
    volumes:
      - VOLUME_PRODUCT_DB:/var/lib/postgresql/data
  customer_db:
    image: postgres:16
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: customer_db
      POSTGRES_USER: customer
      POSTGRES_PASSWORD: customer
    volumes:
      - VOLUME_CUSTOMER_DB:/var/lib/postgresql/data

  order_db:
    image: postgres:16
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: order_db
      POSTGRES_USER: order
      POSTGRES_PASSWORD: order
    volumes:
      - VOLUME_ORDER_DB:/var/lib/postgresql/data

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - microservices-network
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "orderCreationTopic"
    networks:
      - microservices-network

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge
volumes:
  VOLUME_PRODUCT_DB:
  VOLUME_CUSTOMER_DB:
  VOLUME_ORDER_DB:
