version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak
    environment:
      DB_VENDOR: h2
      KEYCLOAK_ADMIN : admin
      KEYCLOAK_ADMIN_PASSWORD : admin
    command: start-dev
    ports:
      - "8090:8080"
    volumes:
      - keycloak_data:/opt/jboss/keycloak/standalone/data

  product_db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: product_db
      POSTGRES_USER: product
      POSTGRES_PASSWORD: product
    volumes:
      - VOLUME_PRODUCT_DB:/var/lib/postgresql/data
  customer_db:
    image: postgres:16
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: customer_db
      POSTGRES_USER: customer
      POSTGRES_PASSWORD: customer
    volumes:
      - VOLUME_CUSTOMER_DB:/var/lib/postgresql/data

  order_db:
    image: postgres:16
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: order_db
      POSTGRES_USER: order
      POSTGRES_PASSWORD: order
    volumes:
      - VOLUME_ORDER_DB:/var/lib/postgresql/data
  payment_db:
    image: postgres:16
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: payment_db
      POSTGRES_USER: payment
      POSTGRES_PASSWORD: payment
    volumes:
      - VOLUME_PAYMENT_DB:/var/lib/postgresql/data
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - microservices-network
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "orderCreationTopic,otp"
    networks:
      - microservices-network
  redis:
    image: redis
    container_name: redis_container
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: redis_password
    volumes:
      - redis_data:/data
#  zipkin:
#    container_name: zipkin
#    image: openzipkin/zipkin
#    ports:
#      - "9411:9411"
#    networks:
#      - microservices-network

networks:
  microservices-network:
    driver: bridge

volumes:
  VOLUME_PRODUCT_DB:
  VOLUME_CUSTOMER_DB:
  VOLUME_ORDER_DB:
  VOLUME_PAYMENT_DB:
  keycloak_data:
    driver: local
  redis_data:
    driver: local
