version: '3.8'

services:
  product_db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: product_db
      POSTGRES_USER: product
      POSTGRES_PASSWORD: product

  customer_db:
    image: postgres:16
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: customer_db
      POSTGRES_USER: customer
      POSTGRES_PASSWORD: customer
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "test_topic:1:3"