spring:
  application:
    name: notification-service
  mail:
    host: smtp.gmail.com
    port: 465
    username: # gmail account
    password: #2-step app verification password from gmail
    protocol: smtps
    default-encoding: UTF-8
  # sender: can be set Sender linked to username
server:
  port: 8090

kafka:
  topic:
    otp: otp
mail:
  subject:
    otp: "Account confirmation"