spring:
  application:
    name: order-service
  config:
    import: optional:configserver:127.0.0.1:8888
  datasource:
    url: jdbc:postgresql://127.0.0.1:5434/order_db
    username: order
    password: order
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    liquibase-schema: public
    default-schema: public
    change-log: classpath:db/changelog/Initializer.xml
  cloud:
    openfeign:
      autoconfiguration:
        jackson:
          enabled: true
server:
  port: 8082
feign:
  clients:
    product:
      name: product-client
      url: http://127.0.0.1:8080
    customer:
      name: customer-client
      url: http://127.0.0.1:8081
kafka:
  topic:
    save_order: topic_save_order
    modify_order: topic_modify_order
    modify_product: topic_modify_product

jwt:
  secretKey: 9CA722EACC9EDE9639E2A26BBEFFEC3B8711