spring:
  config:
    import: optional:configserver:127.0.0.1:8888
  datasource:
    url: jdbc:postgresql://127.0.0.1:5434/order_db
    username: order
    password: order
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    liquibase-schema: public
    default-schema: public
    change-log: classpath:db/changelog/Initializer.xml
  cloud:
    openfeign:
      autoconfiguration:
        jackson:
          enabled: true
  security:
    oauth2:
      keycloak-url: http://127.0.0.1:8090
      keycloak-realm: master  #You have to create realm "online-store" in keycloak
      keycloak-base: ${spring.security.oauth2.keycloak-url}/realms/${spring.security.oauth2.keycloak-realm}
      keycloak-token: /realms/${spring.security.oauth2.keycloak-realm}/protocol/openid-connect/token
      resourceserver:
        jwt:
          issuer-uri: ${spring.security.oauth2.keycloak-base}
          jwk-set-uri: ${spring.security.oauth2.keycloak-base}/protocol/openid-connect/certs
      client:
        provider:
          keycloak:
            issuer-uri: ${spring.security.oauth2.keycloak-base}
            token-uri: ${spring.security.oauth2.keycloak-base}/protocol/openid-connect/token
            user-info-uri: ${spring.security.oauth2.keycloak-base}/protocol/openid-connect/userinfo
            authorization-uri: ${spring.security.oauth2.keycloak-base}/protocol/openid-connect/auth
            user-name-attribute: preferred_username
        registration:
          keycloak:
            provider: keycloak
            client-id: order-service #You have to create client "customer-service" in keycloak
            client-secret: Eqc5gOVD7JoRDcOZ6nJ0r2YnPUxk5ZP4 #client secret here
            authorization-grant-type: client_credentials
server:
  port: 8082
web:
  clients:
    product:
      url: http://127.0.0.1:8082
kafka:
  topic:
    save_order: topic_save_order
    modify_order: topic_modify_order
    modify_product: topic_modify_product
